name: Publish NuGet Package

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  publish:
    name: Publish to NuGet.org
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          cache: true
          cache-dependency-path: |
            CoverageChecker.slnx
            global.json
            .config/dotnet-tools.json
            **/Directory.Build.props
            **/Directory.Packages.props
            **/*.csproj
      - name: Restore Tools
        run: dotnet tool restore
      - name: Build
        run: dotnet build CoverageChecker.slnx --configuration Release
      - name: Test
        run: dotnet test CoverageChecker.slnx --configuration Release --no-build --settings .runsettings
      - name: Pack
        run: dotnet pack CoverageChecker.slnx --configuration Release --no-build --output artifacts/package
      - name: Authenticate with NuGet
        uses: nuget/login@8d196754b4036150537f80ac539e15c2f1028841 # v1
        id: nuget-auth
        with:
          user: ${{ secrets.NUGET_USERNAME }}
      - name: Push to NuGet.org
        run: dotnet nuget push "artifacts/package/*.nupkg" --api-key ${{ steps.nuget-auth.outputs.nuget_api_key }} --source https://api.nuget.org/v3/index.json --skip-duplicate
